import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@/ui/Button";
import { styled } from "@/stitches.config";
import { Link } from "react-router-dom";

const LinkButton = styled(Link, Button, {
  cursor: "pointer",
  // fix issue with gradient on top of button
  zIndex: 1,
  defaultVariants: {
    variant: "solid",
  },
});

export const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.heading}>Make your music live forever</h1>
        </div>
        <LinkButton
          to={{
            pathname: "/upload",
          }}
        >
          Create a new release
        </LinkButton>
      </main>
    </>
  );
};
