import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@/ui/Button";
import { styled } from "@/stitches.config";
import { Link } from "react-router-dom";
import { useConnect } from "@/hooks/useConnect";
import { ConnectWallet } from "../wallet/ConnectWallet";

const LinkButton = styled(Link, Button, {
  cursor: "pointer",
  // fix issue with gradient on top of button
  zIndex: 1,
  defaultVariants: {
    variant: "solid",
  },
});

export const Home = () => {
  const { walletAddress, connecting } = useConnect();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.heading}>Make your music live forever</h1>
        </div>
        {!walletAddress ? (
          <ConnectWallet
            permissions={[
              "ACCESS_ADDRESS",
              "DISPATCH",
              "SIGN_TRANSACTION",
              "ACCESS_ARWEAVE_CONFIG",
              "ACCESS_PUBLIC_KEY",
              "SIGNATURE",
            ]}
            providers={{
              arconnect: true,
              arweaveApp: false,
            }}
            appName="Radar"
          >
            <Button
              css={{
                zIndex: 0,
                fontWeight: 400,
                fontSize: "$3",
              }}
              variant="solid"
            >
              {connecting ? "Connecting..." : "Connect wallet"}
            </Button>
          </ConnectWallet>
        ) : (
          <LinkButton
            to={{
              pathname: "/upload",
            }}
          >
            Create a new release
          </LinkButton>
        )}
      </main>
    </>
  );
};
